In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import requests
import os
from pprint import pprint

In [2]:
games_detailed = os.path.join("01_Resources", "archive", "games_details.csv")
games = os.path.join("01_Resources", "archive", "games.csv")
players = os.path.join("01_Resources", "archive", "players.csv")
ranking = os.path.join("01_Resources", "archive", "ranking.csv")
teams = ranking = os.path.join("01_Resources", "archive", "teams.csv")
games_det_df = pd.read_csv(games_detailed)
games_df = pd.read_csv(games)
players_df = pd.read_csv(players)
rankings_df = pd.read_csv(ranking)
teams_df = pd.read_csv(teams)

/Users/griffinmccalla/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
def describe_df(df):
    print(f'''

Shape of Data Frame:
{df.shape}

Name of Columns: 
{df.columns} 


Length of Columns: {len(df.columns)}

Length of df: {len(df)}

COLUMNS DESCRIBED:

{df.describe()}

DATA TYPES: 

{df.dtypes}

Length of df: {len(df)}''')

In [4]:
print('''
===========================
        games_det_df
===========================
''')

describe_df(games_det_df)
print('''
===========================
        games_df
===========================
''')
describe_df(games_df)
print('''
===========================
        players_df
===========================
''')
describe_df(players_df)

print('''
===========================
        rankings_df
===========================
''')
describe_df(rankings_df)
print('''
===========================
          teams_df
===========================
''')
describe_df(teams_df)

===========================
        games_det_df
===========================



Shape of Data Frame:
(626111, 29)

Name of Columns:
Index(['GAME_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_CITY', 'PLAYER_ID',
       'PLAYER_NAME', 'NICKNAME', 'START_POSITION', 'COMMENT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TO', 'PF', 'PTS',
       'PLUS_MINUS'],
      dtype='object')


Length of Columns: 29

Length of df: 626111

COLUMNS DESCRIBED:

            GAME_ID       TEAM_ID     PLAYER_ID            FGM            FGA  \
count  6.261110e+05  6.261110e+05  6.261110e+05  523751.000000  523751.000000
mean   2.164553e+07  1.610613e+09  3.451868e+05       3.574498       7.878062
std    5.656110e+06  8.649604e+00  7.461713e+06       3.019116       5.657840
min    1.030000e+07  1.610613e+09  1.500000e+01       0.000000       0.000000
25%    2.060092e+07  1.610613e+09  2.419000e+03       1.000000       3.000000
50%    2.120022e+07  1.610613e+09  2.011440e+05       3.000000       7.000000
75%    2.170020e+07  1.610613e+09  2.030920e+05       5.000000      11.000000
max    5.200021e+07  1.610613e+09  1.962938e+09      28.000000      50.000000

              FG_PCT           FG3M          FG3A        FG3_PCT  \
count  523751.000000  523751.000000  523751.00000  523751.000000
mean        0.415843       0.753051       2.11503       0.197427
std         0.251636       1.205652       2.52168       0.289293
min         0.000000       0.000000       0.00000       0.000000
25%         0.250000       0.000000       0.00000       0.000000
50%         0.429000       0.000000       1.00000       0.000000
75%         0.571000       1.000000       3.00000       0.375000
max         1.000000      14.000000      24.00000       1.000000

                 FTM  ...           OREB           DREB            REB  \
count  523751.000000  ...  523751.000000  523751.000000  523751.000000
mean        1.738716  ...       1.028187       3.026999       4.055187
std         2.356272  ...       1.401890       2.685872       3.487341
min         0.000000  ...       0.000000       0.000000       0.000000
25%         0.000000  ...       0.000000       1.000000       1.000000
50%         1.000000  ...       1.000000       2.000000       3.000000
75%         3.000000  ...       2.000000       4.000000       6.000000
max        26.000000  ...      18.000000      25.000000      31.000000

                AST            STL            BLK             TO  \
count  523751.00000  523751.000000  523751.000000  523751.000000
mean        2.09036       0.722950       0.461782       1.325151
std         2.46903       0.974351       0.865591       1.402568
min         0.00000       0.000000       0.000000       0.000000
25%         0.00000       0.000000       0.000000       0.000000
50%         1.00000       0.000000       0.000000       1.000000
75%         3.00000       1.000000       1.000000       2.000000
max        25.00000      10.000000      12.000000      12.000000

                  PF            PTS     PLUS_MINUS
count  523751.000000  523751.000000  500090.000000
mean        2.006984       9.640753      -0.000356
std         1.503485       8.039700      10.611897
min         0.000000       0.000000     -57.000000
25%         1.000000       3.000000      -7.000000
50%         2.000000       8.000000       0.000000
75%         3.000000      14.000000       6.000000
max        15.000000      81.000000      57.000000

[8 rows x 22 columns]

DATA TYPES:

GAME_ID                int64
TEAM_ID                int64
TEAM_ABBREVIATION     object
TEAM_CITY             object
PLAYER_ID              int64
PLAYER_NAME           object
NICKNAME              object
START_POSITION        object
COMMENT               object
MIN                   object
FGM                  float64
FGA                  float64
FG_PCT               float64
FG3M                 float64
FG3A                 float64
FG3_PCT              float64
FTM                  float64
FTA                  float64
FT_PCT               float64
OREB                 float64
DREB                 float64
REB                  float64
AST                  float64
STL                  float64
BLK                  float64
TO                   float64
PF                   float64
PTS                  float64
PLUS_MINUS           float64
dtype: object

Length of df: 626111

===========================
        games_df
===========================



Shape of Data Frame:
(25024, 21)

Name of Columns:
Index(['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID',
       'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home',
       'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away',
       'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away',
       'REB_away', 'HOME_TEAM_WINS'],
      dtype='object')


Length of Columns: 21

Length of df: 25024

COLUMNS DESCRIBED:

            GAME_ID  HOME_TEAM_ID  VISITOR_TEAM_ID        SEASON  \
count  2.502400e+04  2.502400e+04     2.502400e+04  25024.000000
mean   2.167942e+07  1.610613e+09     1.610613e+09   2011.513867
std    5.579698e+06  8.636816e+00     8.656774e+00      5.228157
min    1.030000e+07  1.610613e+09     1.610613e+09   2003.000000
25%    2.060090e+07  1.610613e+09     1.610613e+09   2007.000000
50%    2.120001e+07  1.610613e+09     1.610613e+09   2012.000000
75%    2.170012e+07  1.610613e+09     1.610613e+09   2016.000000
max    5.200021e+07  1.610613e+09     1.610613e+09   2021.000000

       TEAM_ID_home      PTS_home   FG_PCT_home   FT_PCT_home  FG3_PCT_home  \
count  2.502400e+04  24925.000000  24925.000000  24925.000000  24925.000000
mean   1.610613e+09    102.853200      0.460177      0.759202      0.356024
std    8.636816e+00     13.124773      0.056695      0.100675      0.112786
min    1.610613e+09     36.000000      0.250000      0.143000      0.000000
25%    1.610613e+09     94.000000      0.421000      0.696000      0.286000
50%    1.610613e+09    102.000000      0.459000      0.765000      0.357000
75%    1.610613e+09    111.000000      0.500000      0.828000      0.429000
max    1.610613e+09    168.000000      0.684000      1.000000      1.000000

           AST_home      REB_home  TEAM_ID_away      PTS_away   FG_PCT_away  \
count  24925.000000  24925.000000  2.502400e+04  24925.000000  24925.000000
mean      22.666760     43.302106  1.610613e+09     99.998114      0.448975
std        5.168521      6.610744  8.656774e+00     13.251149      0.055501
min        6.000000     15.000000  1.610613e+09     33.000000      0.244000
25%       19.000000     39.000000  1.610613e+09     91.000000      0.411000
50%       22.000000     43.000000  1.610613e+09    100.000000      0.448000
75%       26.000000     48.000000  1.610613e+09    109.000000      0.486000
max       50.000000     72.000000  1.610613e+09    168.000000      0.674000

        FT_PCT_away  FG3_PCT_away      AST_away      REB_away  HOME_TEAM_WINS
count  24925.000000  24925.000000  24925.000000  24925.000000    25024.000000
mean       0.757640      0.349365     21.314022     42.021745        0.588875
std        0.103315      0.111003      5.122301      6.524002        0.492048
min        0.143000      0.000000      4.000000     19.000000        0.000000
25%        0.692000      0.278000     18.000000     38.000000        0.000000
50%        0.763000      0.350000     21.000000     42.000000        1.000000
75%        0.829000      0.421000     25.000000     46.000000        1.000000
max        1.000000      1.000000     46.000000     81.000000        1.000000

DATA TYPES:

GAME_DATE_EST        object
GAME_ID               int64
GAME_STATUS_TEXT     object
HOME_TEAM_ID          int64
VISITOR_TEAM_ID       int64
SEASON                int64
TEAM_ID_home          int64
PTS_home            float64
FG_PCT_home         float64
FT_PCT_home         float64
FG3_PCT_home        float64
AST_home            float64
REB_home            float64
TEAM_ID_away          int64
PTS_away            float64
FG_PCT_away         float64
FT_PCT_away         float64
FG3_PCT_away        float64
AST_away            float64
REB_away            float64
HOME_TEAM_WINS        int64
dtype: object

Length of df: 25024

===========================
        players_df
===========================



Shape of Data Frame:
(7228, 4)

Name of Columns:
Index(['PLAYER_NAME', 'TEAM_ID', 'PLAYER_ID', 'SEASON'], dtype='object')


Length of Columns: 4

Length of df: 7228

COLUMNS DESCRIBED:

            TEAM_ID     PLAYER_ID       SEASON
count  7.228000e+03  7.228000e+03  7228.000000
mean   1.610613e+09  2.355862e+06  2014.159934
std    8.723521e+00  6.106688e+07     3.126216
min    1.610613e+09  2.440000e+02  2009.000000
25%    1.610613e+09  2.007680e+05  2012.000000
50%    1.610613e+09  2.023465e+05  2014.000000
75%    1.610613e+09  2.039100e+05  2017.000000
max    1.610613e+09  1.962938e+09  2019.000000

DATA TYPES:

PLAYER_NAME    object
TEAM_ID         int64
PLAYER_ID       int64
SEASON          int64
dtype: object

Length of df: 7228

===========================
        rankings_df
===========================



Shape of Data Frame:
(30, 14)

Name of Columns:
Index(['LEAGUE_ID', 'TEAM_ID', 'MIN_YEAR', 'MAX_YEAR', 'ABBREVIATION',
       'NICKNAME', 'YEARFOUNDED', 'CITY', 'ARENA', 'ARENACAPACITY', 'OWNER',
       'GENERALMANAGER', 'HEADCOACH', 'DLEAGUEAFFILIATION'],
      dtype='object')


Length of Columns: 14

Length of df: 30

COLUMNS DESCRIBED:

       LEAGUE_ID       TEAM_ID     MIN_YEAR  MAX_YEAR  YEARFOUNDED  \
count       30.0  3.000000e+01    30.000000      30.0    30.000000
mean         0.0  1.610613e+09  1969.700000    2019.0  1969.700000
std          0.0  8.803408e+00    16.698441       0.0    16.698441
min          0.0  1.610613e+09  1946.000000    2019.0  1946.000000
25%          0.0  1.610613e+09  1952.000000    2019.0  1952.000000
50%          0.0  1.610613e+09  1970.000000    2019.0  1970.000000
75%          0.0  1.610613e+09  1979.000000    2019.0  1979.000000
max          0.0  1.610613e+09  2002.000000    2019.0  2002.000000

       ARENACAPACITY
count      26.000000
mean    18553.307692
std      3916.923362
min         0.000000
25%     18641.500000
50%     19131.000000
75%     19790.750000
max     21711.000000

DATA TYPES:

LEAGUE_ID               int64
TEAM_ID                 int64
MIN_YEAR                int64
MAX_YEAR                int64
ABBREVIATION           object
NICKNAME               object
YEARFOUNDED             int64
CITY                   object
ARENA                  object
ARENACAPACITY         float64
OWNER                  object
GENERALMANAGER         object
HEADCOACH              object
DLEAGUEAFFILIATION     object
dtype: object

Length of df: 30

===========================
          teams_df
===========================



Shape of Data Frame:
(30, 14)

Name of Columns:
Index(['LEAGUE_ID', 'TEAM_ID', 'MIN_YEAR', 'MAX_YEAR', 'ABBREVIATION',
       'NICKNAME', 'YEARFOUNDED', 'CITY', 'ARENA', 'ARENACAPACITY', 'OWNER',
       'GENERALMANAGER', 'HEADCOACH', 'DLEAGUEAFFILIATION'],
      dtype='object')


Length of Columns: 14

Length of df: 30

COLUMNS DESCRIBED:

       LEAGUE_ID       TEAM_ID     MIN_YEAR  MAX_YEAR  YEARFOUNDED  \
count       30.0  3.000000e+01    30.000000      30.0    30.000000
mean         0.0  1.610613e+09  1969.700000    2019.0  1969.700000
std          0.0  8.803408e+00    16.698441       0.0    16.698441
min          0.0  1.610613e+09  1946.000000    2019.0  1946.000000
25%          0.0  1.610613e+09  1952.000000    2019.0  1952.000000
50%          0.0  1.610613e+09  1970.000000    2019.0  1970.000000
75%          0.0  1.610613e+09  1979.000000    2019.0  1979.000000
max          0.0  1.610613e+09  2002.000000    2019.0  2002.000000

       ARENACAPACITY
count      26.000000
mean    18553.307692
std      3916.923362
min         0.000000
25%     18641.500000
50%     19131.000000
75%     19790.750000
max     21711.000000

DATA TYPES:

LEAGUE_ID               int64
TEAM_ID                 int64
MIN_YEAR                int64
MAX_YEAR                int64
ABBREVIATION           object
NICKNAME               object
YEARFOUNDED             int64
CITY                   object
ARENA                  object
ARENACAPACITY         float64
OWNER                  object
GENERALMANAGER         object
HEADCOACH              object
DLEAGUEAFFILIATION     object
dtype: object

Length of df: 30

In [5]:
games_det_df.name

AttributeError: 'DataFrame' object has no attribute 'name'